# Generated by Django 2.1.5 on 2019-06-05 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_relationship_4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('artists', models.ManyToManyField(related_name='issues', to='model_relationship_4.Artist')),
            ],
        ),
        migrations.RemoveField(
            model_name='writer',
            name='comic',
        ),
        migrations.AlterField(
            model_name='comic',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comics', to='model_relationship_4.Artist'),
        ),
        migrations.AddField(
            model_name='issue',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='model_relationship_4.Comic'),
        ),
        migrations.AddField(
            model_name='issue',
            name='writers',
            field=models.ManyToManyField(related_name='issues', to='model_relationship_4.Writer'),
        ),
    ]
